kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

trigger:
  branch:
  - master
  event:
  - push

clone:
  depth: 1

steps:
- name: build
  environment:
    GOOS: linux
    GOARCH: amd64
    CGO_ENABLED: "0"
  commands:
  - go build
  - docker build -t aulang/site .

- name: stop-service
  commands:
  - docker stop site
  - docker rm site

- name: deploy-frontend
  commands:
  - rm -rf /usr/share/nginx/site/
  - cp -rf ./UI/ /usr/share/nginx/site

- name: deploy-backend
  commands:
  - rm -rf /var/log/site/*
  - docker run -d -v /var/log/site:/var/log/site --name=site --net=host --restart=always aulang/site
