stages:
  - build
  - stop
  - deploy

build_image:
  stage: build
  only:
    - master
  script:
    - export GOOS=linux
    - export GOARCH=amd64
    - export CGO_ENABLED=0
    - export GOPROXY=https://goproxy.cn
    - go build
    - docker build -t aulang/site .

stop_service:
  stage: stop
  only:
    - master
  script:
    - docker stop site
    - docker rm site

delete_none_image:
  stage: deploy
  only:
    - master
  allow_failure: true
  script:
    - docker rmi $(docker images | grep "none" | awk '{print $3}')

deploy-backend:
  stage: deploy
  only:
    - master
  script:
    - docker run -d -p 8081:8081 -v /var/log/site:/var/log/site --name=site --restart=always aulang/site
