iris:
  port: 8081
  charset: "UTF-8"
  enable-optimizations: true
  time-format: 2006-01-02 15:04:05
  remote-addr-headers:
    - X-Real-Ip
    - X-Forwarded-For

mongodb:
  uri: mongodb://${STROAGE_IP:127.0.0.1}:27027
  database: site
  username: ${MONGO_USERNAME:xxx}
  password: ${MONGO_PASSWORD:xxxxxx}

minio:
  endpoint: ${STROAGE_IP:127.0.0.1}:9000
  accessKey: ${MINIO_ACCESS_KEY:xxx}
  secretKey: ${MINIO_SECRET_KEY:xxxxxx}
  useSSL: false
