iris:
  port: 8081
  charset: "UTF-8"
  enable-optimizations: true
  time-format: 2006-01-02 15:04:05
  remote-addr-headers:
    - X-Real-Ip
    - X-Forwarded-For

mongodb:
  uri: mongodb://127.0.0.1:27017
  database: site

minio:
  endpoint: aulang.cn:9000
  accessKey: lsT6BZoh2gWPKUmH
  secretKey: A7Ak1TGQSytK5WmGSRF3VWQFYHYEVVZG
  useSSL: false
